controller_manager:
  ros__parameters:
    update_rate: 250

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    leg_position_controller:
      type: position_controllers/JointGroupPositionController


diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["FL_foot_joint", "RL_foot_joint"]
    right_wheel_names: ["FR_foot_joint", "RR_foot_joint"]

    wheel_separation: 0.50
    wheel_radius: 0.09

    publish_rate: 50.0
    odom_frame_id: "odom"
    base_frame_id: "base"
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001]

    enable_odom_tf: true
    cmd_vel_timeout: 0.25
    use_stamped_vel: false


leg_position_controller:
  ros__parameters:
    joints:
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint

    interface_name: position
