odom_to_tf:
  ros__parameters:
    frame_id: "odom"
    child_frame_id: "base_footprint"
    odom_yaw_offset: 1.57079632679
    odom_topic_1: "/lio_sam/mapping/odometry"
    odom_topic_2: ""
    pose_topic: ""
    sport_mode_topic: ""
